config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :boards, only: [:create]

  resources :solutions, only: [:create, :show] do
    resources :moves, only: [:create]
    resource :copy, only: [:create], controller: "solution_copies"
  end

  #resources :robots, only: []

end

app/models/solution.rb
class Solution < ActiveRecord::Base
  belongs_to :original_board, class_name: "Board"
  belongs_to :board
  has_many :spaces, through: :board
  has_many :goals, through: :spaces
  has_many :walls, through: :spaces
  has_many :robots, through: :spaces
  has_many :moves, through: :robots

  after_create :dup_original_board

  def dup_original_board
    self.update(board: CopyBoard.run(board: original_board))
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  def show
    @solution = Solution.includes(
      :board,
      :goals,
      :robots,
      :spaces,
      :walls,
    ).find(params[:id])
    @move = Move.new
    if @solution.board.goal.completed?
      flash.now[:notice] = "Solved!"
    end
  end
end

app/views/solutions/show.html.haml
.container
  .row
    .col-xs-12
      = render @solution.board
    #h3
      Moves:
      = @solution.board.moves.count
    = link_to "Reset", solution_copy_path(@solution), method: "POST", class: 'btn btn-default'
    = link_to 'New Game', boards_path, method: "POST", class: 'btn btn-default'
    #moves_form.col-xs-12
      %h1 New Move
      = render 'moves/form'